server:
  port: 0
queue:
  series: series-queue
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: movie-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8080
  datasource:
    url: jdbc:mysql://localhost:3306/dh
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  rabbitmq:
    username: admin
    password: admin
    host: localhost
    port: 5672
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8888/eureka}
  instance:
    preferIpAddress: true