server:
  port: 0
spring:
  application:
    name: movie-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8080
  datasource:
    url: jdbc:h2:mem:movies
    username: admin
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8888/eureka}
  instance:
    preferIpAddress: true