spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    addresses: localhost:5672
    username: admin
    password: admin
    virtual-host: app_vhost
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
    sender:
      type:rabbit

  application:
    name: catalog-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8888/eureka}
  instance:
    preferIpAddress: true