server:
  port: 8080

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://Users/juancruzpressacco/repos/eureka-server
          #uri: ssh:git@github.com:beludominguez/dh-eureka.git
          search-paths: config-server/config
          default-label: master
